trigger: none
pr: none

resources:
 pipelines:
   - pipeline: P1
     source: build_aspdotnetcore
     trigger: true

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: VMDeploy
    displayName: web
    pool: demopool
    environment:
      name: VM-Env
      resourceType: VirtualMachine
    strategy:
      rolling:
        maxBatchSize: 1
        preDeploy:
          steps:
            - script: echo Hello, world! This is pre-deploy
              displayName: 'Run a one-line script'
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: 'Create Website'
            inputs:
              WebsiteName: 'Default Web Site'
              AddBinding: True
              Bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"80","hostname":"","sslThumbprint":"","sniFlag":false}]}'
              ParentWebsiteNameForVD: 'Default Web Site'
              ParentWebsiteNameForApplication: 'Default Web Site'
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy application to Website'
            inputs:
              WebSiteName: 'Default Web Site'
              Package: '$(Pipeline.Workspace)/**/*.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true

        routeTraffic:
          steps:
            - script: echo Hello, world! This is routeTraffic
              displayName: 'Run a one-line script'

        postRouteTraffic:
          steps:
            - script: echo Hello, world! This is postRouteTraffic
              displayName: 'Run a one-line script'

        on:
          failure:
            steps:
            - script: echo Hello, world! This is on failure
              displayName: 'Run a one-line script'

          success:
            steps:
            - script: echo Hello, world! This is on success
              displayName: 'Run a one-line script' 

