
trigger: none
resources:
 pipelines:
 - pipeline: build
   source: Niadak-VM-CI
   trigger: 
    branches:
    - master

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: VMDeploy
    displayName: web
    environment:
      name: Niadak-VM-Env
      #name: NiadakEnvironment01
      resourceType: VirtualMachine
    strategy:
      runOnce:
      #rolling:
        #maxParallel: 2
        preDeploy:
          steps:
            - script: echo Hello, world! This is pre-deploy
              displayName: 'Run a one-line script'
        deploy:
          steps:
          - script: echo Hello, world! This is deploy
            displayName: 'Run a one-line script' 

        routeTraffic:
          steps:
            - script: echo Hello, world! This is routeTraffic
              displayName: 'Run a one-line script'

        postRouteTraffic:
          steps:
            - script: echo Hello, world! This is postRouteTraffic
              displayName: 'Run a one-line script'

        on:
          failure:
            steps:
            - script: echo Hello, world! This is on failure
              displayName: 'Run a one-line script'

          success:
            steps:
            - script: echo Hello, world! This is on success
              displayName: 'Run a one-line script' 

